#pragma once

// internal
#include "common.hpp"
#include "tiles.hpp"
#include "pathing.hpp"

// stlib
#include <vector>
#include <random>
#include <map>
#include <chrono>

#define SDL_MAIN_HANDLED
#include <SDL.h>
#include <SDL_mixer.h>

#include "render_system.hpp"

// Container for all our entities and game logic.
// Individual rendering / updates are deferred to the update() methods.
class WorldSystem
{
public:
	WorldSystem();

	// creates main window
	GLFWwindow* create_window();

	// starts and loads music and sound effects
	bool start_and_load_sounds();

	// call to close the window
	void close_window();

	// starts the game
	void init(RenderSystem* renderer);

	// releases all associated resources
	~WorldSystem();

	// steps the game ahead by ms milliseconds
	bool step(float elapsed_ms);

	// check for collisions generated by the physics system
	void handle_collisions();

	// should the game be over ?
	bool is_over() const;

	// A2: update the window caption (title)
	void update_window_caption();

	// A2: update the grid outlines to show the currently hovered tile
	void update_outline();

	// A2: report the current game screen
	GAME_SCREEN_ID get_game_screen() { return game_screen; }

	// A2: saving and loading levels
	std::string world_level_filename = "level0.txt"; // start with level0
	bool load_level(const std::string& filename);
	bool save_level(const std::string& filename);
	bool find_path(ivec2 startPos, std::vector<ivec2>& path);
	// to check if there is a valid path in current level
	bool has_valid_path = false;
	std::vector<ivec2> get_neighbors(const ivec2& pos);

	// A2: world level
	bool find_first_start_tile(glm::ivec2& start_tile);
	bool find_first_exit_tile(glm::ivec2& exit_tile);

	// in order for HUD in main.cpp to be able to access these
	int invader_amount = 0;		// keep track of the number of invaders currently on the map
	int level_invader_max_amount = 10; // 10 by default, but actually (current level + 1) * INVADER_MAX_AMOUNT

	// keep track of the current score of the whole game
	int curr_score = 0;
	// keep track of the high score of the whole game
	int high_score = 0;
	// load and save the high score
	bool load_high_score(const std::string& filename);
	bool save_high_score(const std::string& filename);
	bool new_high_score;
	float new_high_score_timer_ms = 0.f; // counts down from 2000ms
	bool new_high_score_shown = false; // shows once per game

	// check if it's victory
	bool is_victory;

	// keep track of the max towers of the whole game
	int max_towers;
	std::chrono::steady_clock::time_point last_tower_create;

	// keep track of the invader points animation
	std::vector<FloatingText> floating_texts;

private:

	float mouse_pos_x = 0.0f;
	float mouse_pos_y = 0.0f;

	// 2D array to store the tiles of every level for A*
	std::vector<std::vector<tile_dir>> level_tiles;
	ivec2 start_tile;
	ivec2 exit_tile;

	// to better support uses with track pads and macOS, holding SHIFT + LEFT-CLICK will be a right-click
	bool shift_key_pressed = false;
	// to check if the current level has been visualized or not by the player pressing O
	bool path_visualized = false;
	// to check if the player switched between playing and drawing screen mid game
	bool map_edited = false;

	// A2: default tile (for drawing map)
	TEXTURE_ASSET_ID drawing_tile = TEXTURE_ASSET_ID::MAPTILE_121;

	// input callback functions
	void on_key(int key, int, int action, int mod);
	void on_mouse_move(vec2 pos);
	void on_mouse_button_pressed(int button, int action, int mods);

	// helper function to check if a tile is on any of the invader paths
	bool is_tile_on_path(int tile_x, int tile_y);

	// helper to check if the game is victory or defeat
	void game_over_fade_out(float elapsed_ms_since_last_update);

	// restart level
	void restart_game(bool reset_score);

	// OpenGL window handle
	GLFWwindow* window;

	float next_invader_spawn;
	int invader_spawn_rate_ms;	// see default value in common.hpp

	// Number of invaders stopped by the towers, displayed in the window title
	unsigned int points;

	// Game state
	RenderSystem* renderer;
	float current_speed;
	// A2 -> A3 TODO: need to show the intro screen first
	GAME_SCREEN_ID game_screen = GAME_SCREEN_ID::INTRO;

	// grid
	std::vector<Entity> grid_lines;

	// music references
	Mix_Music* background_music;
	Mix_Chunk* invader_hit_sound;
	Mix_Chunk* tower_hit_sound;

	// C++ random number generator
	std::default_random_engine rng;
	std::uniform_real_distribution<float> uniform_dist; // number between 0..1
};
